---
 version: '3'

 services: 
  mydb: 
   image: mysql:5
   environment: 
    MYSQL_ROOT_PASSWORD: katakam@007

  mysite: 
   image: wordpress
   ports: 
    - 8888:80
   links: 
    - mydb:mysql
...
